target_default: 0_config

packages:
  - sp
  - scipiper
  - dplyr

sources:
  - 0_config/code/nldas_cube_utils.R
  - 0_config/code/nldas_feather_utils.R
  
targets:
  0_config: 
    depends: 
      - 1_nldas_subset_rmk.yml
      - 1_nldas_append_rmk.yml
  
  nldas_subset_time:
    command: c(t0=I(0), t1 = I(12300))#345551))
    
  nldas_time_chunk:
    command: c(I(10000))
    
  nldas_cells:
    command: list(x=I(c(221,221,344,344,223)), y=I(c(132,196,132,196,141)), variables=I(c('dlwrfsfc','pressfc','apcpsfc','vgrd10m','ugrd10m','dswrfsfc','spfh2m','tmp2m'))) # will come from code or spatial data...
      
  nldas_subset_box: # this is a FULL time pull
    command: nldas_diff_box(nldas_cells, '0_config/in/nldas_cells.rds') 
      
  nldas_append_box: # this is a PARTIAL time pull, where partial time could be 0 (complete)
    command: nldas_update_box(nldas_cells, nldas_subset_box) 

  nldas_append_time:
    command: nldas_times_diff(nldas_subset_time, '0_config/in/nldas_times.rds')
    
  nldas_subset_files:
    command: calc_nldas_files(nldas_subset_box, nldas_subset_time, nldas_time_chunk)
  
  nldas_append_files:
    command: calc_nldas_files(nldas_append_box, nldas_append_time, nldas_time_chunk)
  
  nldas_pull_cells:
    command: nldas_diff_cells(nldas_cells, '0_config/in/nldas_cells.rds') 
    
  nldas_cap_cells:
    command: nldas_update_cells(nldas_cells, nldas_pull_cells, '0_config/in/nldas_times.rds')
  
  nldas_subset_plan:
    command: create_cube_task_plan(nldas_subset_files, nc_dir = I("1_nldas_cubes/out"), ind_dir=I('1_nldas_cubes/log'))

  nldas_append_plan:
    command: create_cube_task_plan(nldas_append_files, nc_dir = I("1_nldas_cubes/out"), ind_dir=I('1_nldas_cubes/log'))

  "1_nldas_subset_rmk.yml":
    command: create_cube_task_makefile(target_name, nldas_subset_plan, include = I("0_config_rmk.yml"), packages = I(c('dplyr','ncdf4')), sources = '1_nldas_cubes/code/nccopy_utils.R')
    
  "1_nldas_append_rmk.yml":
    command: create_cube_task_makefile(target_name, nldas_append_plan, include = I("0_config_rmk.yml"), packages = I(c('dplyr','ncdf4')), sources = '1_nldas_cubes/code/nccopy_utils.R')  
  
  #"2_driver_pull_rmk.yml":
 #  command: create_feather_task_makefile(target_name, nldas_subset_files, include = I("0_config_rmk.yml"), nc_dir = I("1_nldas_cubes/out"), ind_dir=I('1_nldas_cubes/log'), packages = I(c('dplyr','ncdf4')), sources = '1_nldas_cubes/code/nccopy_utils.R')
    
