target_default: 0_config

packages:
  - sp
  - scipiper
  - dplyr

sources:
  - 0_config/code/nldas_cube_utils.R
targets:
  0_config: 
    depends: 
      - 1_nldas_subset_rmk.yml
      - 1_nldas_append_rmk.yml
  
  nldas_subset_time:
    command: c(t0=I(0), t1 = I(19))
    
  nldas_time_chunk:
    command: c(I(10))
    
  nldas_cells:
    command: list(x=I(c(231,239,223)), y=I(c(135,135,141)), variables=I(c('dlwrfsfc','pressfc'))) # will come from code or spatial data...
      
  nldas_subset_box: # this is a FULL time pull
    command: nldas_diff_box(nldas_cells, '0_config/in/nldas_cells.rds') 
      
  nldas_append_box: # this is a PARTIAL time pull, where partial time could be 0 (complete)
    command: nldas_update_box(nldas_cells, nldas_subset_box) 

  nldas_append_time:
    command: nldas_times_diff(nldas_subset_time, '0_config/in/nldas_times.rds')
    
  nldas_subset_files:
    command: calc_nldas_files(nldas_subset_box, nldas_subset_time, nldas_time_chunk)
  
  nldas_append_files:
    command: calc_nldas_files(nldas_append_box, nldas_append_time, nldas_time_chunk)

  "1_nldas_subset_rmk.yml":
    command: create_cube_task_makefile(target_name, nldas_subset_files, include = I("0_config_rmk.yml"), nc_dir = I("1_nldas_cubes/out"), ind_dir=I('1_nldas_cubes/log'), packages = I(c('dplyr','ncdf4')), sources = '1_nldas_cubes/code/nccopy_utils.R')
    
  "1_nldas_append_rmk.yml":
    command: create_cube_task_makefile(target_name, nldas_append_files, include = I("0_config_rmk.yml"), nc_dir = I("1_nldas_cubes/out"), ind_dir=I('1_nldas_cubes/log'), packages = I(c('dplyr','ncdf4')), sources = '1_nldas_cubes/code/nccopy_utils.R')  
