target_default: 7_config_merge

packages:
  - dplyr
  - scipiper
  - feather
  - readr
  - rlang
  - raster
  - sf
  - lwgeom
  - maps

sources:
  - 7_config_merge/src/munge_lake_info.R

targets:
  7_config_merge:
    depends:
      - 7_config_merge/out/nml_cd_values.rds.ind
      - 7_config_merge/out/nml_lat_lon_values.rds.ind
      - 7_config_merge/out/nml_H_A_values.rds.ind
      - 7_config_merge/out/nml_len_wid_values.rds.ind
      - 7_config_merge/out/nml_lake_depth_values.rds.ind

  7_config_merge/out/canonical_lakes_area.rds.ind:
    command: munge_lake_area(target_name,
      lakes_ind = '1_crosswalk_fetch/out/canonical_lakes_sf.rds.ind')
  7_config_merge/out/canonical_lakes_area.rds:
    command: gd_get('7_config_merge/out/canonical_lakes_area.rds.ind')

  7_config_merge/out/nml_cd_values.rds.ind:
    command: munge_cd_from_nlcd(target_name,
      nlcd_ind = '4_params_munge/out/nlcd_2011_buffers.rds.ind',
      nlcd_hc_file = '4_params_munge/in/nlcd_class_heights.tsv',
      areas_ind = '7_config_merge/out/canonical_lakes_area.rds.ind')
  7_config_merge/out/nml_cd_values.rds:
    command: gd_get('7_config_merge/out/nml_cd_values.rds.ind')

  7_config_merge/out/nml_lat_lon_values.rds.ind:
    command: munge_lat_lon(target_name,
      centroids_ind = '2_crosswalk_munge/out/centroid_lakes_sf.rds.ind')
  7_config_merge/out/nml_lat_lon_values.rds:
    command: gd_get('7_config_merge/out/nml_lat_lon_values.rds.ind')

  7_config_merge/out/nml_H_A_values.rds.ind:
    command: munge_H_A(target_name,
      areas_ind = '7_config_merge/out/canonical_lakes_area.rds.ind',
      '4_params_munge/out/mndow_bathy.rds.ind',
      '4_params_munge/out/lagos_depths.rds.ind',
      '4_params_munge/out/mglp_depths.rds.ind')
  7_config_merge/out/nml_H_A_values.rds:
    command: gd_get('7_config_merge/out/nml_H_A_values.rds.ind')

  7_config_merge/out/nml_len_wid_values.rds.ind:
    command: munge_wid_len(target_name,
      areas_ind = '7_config_merge/out/canonical_lakes_area.rds.ind')
  7_config_merge/out/nml_len_wid_values.rds:
    command: gd_get('7_config_merge/out/nml_len_wid_values.rds.ind')

  7_config_merge/out/nml_lake_depth_values.rds.ind:
    command: munge_lake_depth(target_name,
      '7_config_merge/out/nml_H_A_values.rds.ind')
  7_config_merge/out/nml_lake_depth_values.rds:
    command: gd_get('7_config_merge/out/nml_lake_depth_values.rds.ind')
