target_default: 7_config_merge

packages:
  - dplyr
  - scipiper
  - feather
  - readr
  - rlang
  - raster
  - sf
  - lwgeom
  - maps

sources:
  - 7_config_merge/src/munge_for_lakeattributes.R

targets:
  7_config_merge:
    depends:
      - 7_config_merge/out/nml_cd_values.rds.ind
      - 7_config_merge/out/nml_lat_lon_values.rds.ind


  7_config_merge/out/nml_cd_values.rds.ind:
    command: munge_cd_from_nlcd(target_name,
      nlcd_ind = '4_params_munge/out/nlcd_2011_buffers.rds.ind',
      nlcd_hc_file = '4_params_munge/in/nlcd_class_heights.tsv',
      areas_ind = '4_params_munge/out/canonical_lakes_area.rds.ind')
  7_config_merge/out/nml_cd_values.rds:
    command: gd_get('7_config_merge/out/nml_cd_values.rds.ind')

  7_config_merge/out/nml_lat_lon_values.rds.ind:
    command: munge_lat_lon(target_name,
      centroids_ind = '2_crosswalk_munge/out/centroid_lakes_sf.rds.ind')
  7_config_merge/out/nml_lat_lon_values.rds:
    command: gd_get('7_config_merge/out/nml_lat_lon_values.rds.ind')
