---
title: "Status of Lake Data for Temperature Modeling"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r firstMap}
library(leaflet)
library(feather)

df <- feather(file.path("8_viz", "inout", "lakes_summary.feather"))
df <- data.frame(df)

col_types <- c("darkblue","dodgerblue","green4","gold1","orange","brown","red")

#df$n_profile_years_size <- df$n_profile_years
#df$n_profile_years_size <- 7*df$n_profile_years_size/(max(df$n_profile_years_size,na.rm = TRUE))

#df$n_profile_years_size[is.na(df$n_profile_years_size)] <- 2

df$popup <- paste0("<table>",
                   "<tr><td>Lake Name:</td><td>",
                   df$GNIS_Name,'</td></tr>',
                   "<tr><td>Site ID:</td><td>",
                   df$site_id,'</td></tr>',
                   "<tr><td># Observations:</td><td>",
                   df$n_obs,'</td></tr>',
                   "<tr><td># Profiles:</td><td>",
                   df$n_profiles,'</td></tr>',
                   "<tr><td>Crosswalked to:</td><td>",
                   df$Lake_Source,'</td></tr>',
                   '</table>')

legend_vals <- c("< 10 profiles", "< 50 profiles", "50+ profiles", "none")

pal <- colorFactor(c("#35B779B3","#31688EB3","#440154B3",'red'), legend_vals)


# Setup groups & filter here
lakes_glm <- dplyr::filter(df, zmax & kw & meteo)
lakes_glm_no_meteo <- dplyr::filter(df, zmax & kw & !meteo)
lakes_pgdl <- dplyr::filter(df, zmax & kw & meteo & n_profiles > 10)
lakes_pgdl_no_meteo <- dplyr::filter(df, zmax & kw & !meteo & n_profiles > 10)
lakes_toha <- dplyr::filter(df, hypsography & kw_file & meteo)
lakes_kw_file_no_kw <- dplyr::filter(df, kw_file, !kw)
lakes_hypso_pipeline <- dplyr::filter(df, hypsography)
lakes_no_hypso_pipeline <- dplyr::filter(df, n_profiles > 50 & !hypsography)
lakes_hypso_digitizing <- dplyr::filter(df, n_profiles > 50 & hypsography_digitizing)
lakes_no_hypso_found <- dplyr::filter(df, n_profiles > 50 & !hypsography & !hypsography_digitizing)

# Create text that appears + order they appear in
groups <- c(
  sprintf("GLM Lake (n=%s)", nrow(lakes_glm)),
  sprintf("GLM, but no meteo (n=%s)", nrow(lakes_glm_no_meteo)),
  sprintf("PGDL Lake (n=%s)", nrow(lakes_pgdl)),
  sprintf("PGDL, but no meteo (n=%s)", nrow(lakes_pgdl_no_meteo)),
  sprintf("TOHA Lake (n=%s)", nrow(lakes_toha)),
  sprintf("Kw_file, no kw (n=%s)", nrow(lakes_kw_file_no_kw)),
  sprintf("Hypsography in pipeline (n=%s)", nrow(lakes_hypso_pipeline)),
  sprintf("Lots of data, no hypso in pipeline (n=%s)", nrow(lakes_no_hypso_pipeline)),
  sprintf("Lots of data, hypso being digitized (n=%s)", nrow(lakes_hypso_digitizing)),
  sprintf("Lots of data, no hypso found yet (n=%s)", nrow(lakes_no_hypso_found))
)

leaflet::leaflet(height = "800px", width = "1000px") %>%
    leaflet::addProviderTiles("CartoDB.Positron") %>%
    leaflet::setView(lng = -92.5, lat = 44.5, zoom=5) %>%
    leaflet::addCircleMarkers(data= lakes_toha,
                              lat=~latitude, lng=~longitude, 
                              group = groups[5],
                              popup= ~popup,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>%
  leaflet::addCircleMarkers(data= lakes_no_hypso_pipeline,
                              lat=~latitude, lng=~longitude, 
                              group = groups[8],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>%
  leaflet::addCircleMarkers(data= lakes_hypso_digitizing,
                              lat=~latitude, lng=~longitude, 
                              group = groups[9],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>% 
  leaflet::addCircleMarkers(data= lakes_no_hypso_found,
                              lat=~latitude, lng=~longitude, 
                              group = groups[10],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>% 
    leaflet::addCircleMarkers(data= lakes_pgdl_no_meteo,
                              lat=~latitude, lng=~longitude, 
                              group = groups[4],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>%
      leaflet::addCircleMarkers(data= lakes_kw_file_no_kw,
                              lat=~latitude, lng=~longitude, 
                              group = groups[6],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>%
      leaflet::addCircleMarkers(data= lakes_hypso_pipeline,
                              lat=~latitude, lng=~longitude, 
                              group = groups[7],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>%
      leaflet::addCircleMarkers(data= lakes_pgdl,
                              lat=~latitude, lng=~longitude, 
                              group = groups[3],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>%
    leaflet::addCircleMarkers(data= lakes_glm,
                              lat=~latitude, lng=~longitude, 
                              group = groups[1],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>%
      leaflet::addCircleMarkers(data= lakes_glm_no_meteo,
                              lat=~latitude, lng=~longitude, 
                              group = groups[2],
                              popup= ~popup ,
                     fillColor = ~pal(obs_category),
                     fillOpacity = 0.8,
                     radius = ~4,
                     stroke=FALSE) %>%
  leaflet::addLegend(data = df, pal = pal,
                     position = 'bottomleft',
                     values=~obs_category,
                     labFormat = leaflet::labelFormat(digits = 0),
                     title = "Number of observations") %>%
  addLayersControl(
    baseGroups = groups,
    #overlayGroups = c("observed","hypsography", "zmax", "kw","kw_file","meteo"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% 
  hideGroup(c("No observations","Observed but no zmax",">100 profiles & no hypsometry"))


```
