# Maximum number of sites for which to request inventory data at one time
target_inv_size: 500

# Approximate maximum number of records to pull in each call to WQP. Recommended number is 500000
target_pull_size: 150
